In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Preprocessing - msa_m2023

In [9]:
# read in data
msa_df = pd.read_excel("../data/raw/MSA_M2023_dl.xlsx")

In [ ]:
# filter detailed O_GROUP
msa_df = msa_df[msa_df["O_GROUP"] == "detailed"]
msa_df = msa_df.reset_index(drop=True)

In [11]:
# convert * and # to NaN
msa_df.replace(r'[\*#]', np.nan, regex=True, inplace=True)

,AREA,AREA_TITLE,AREA_TYPE,PRIM_STATE,NAICS,NAICS_TITLE,I_GROUP,OWN_CODE,OCC_CODE,OCC_TITLE,...,H_MEDIAN,H_PCT75,H_PCT90,A_PCT10,A_PCT25,A_MEDIAN,A_PCT75,A_PCT90,ANNUAL,HOURLY
2,10180,"Abilene, TX",4,TX,0,Cross-industry,cross-industry,1235,11-1011,Chief Executives,...,97.28,NaN,NaN,98490,135280,202340,NaN,NaN,NaN,NaN
3,10180,"Abilene, TX",4,TX,0,Cross-industry,cross-industry,1235,11-1021,General and Operations Managers,...,37.19,57.85,86.97,34440,49430,77360,120330,180900,NaN,NaN
4,10180,"Abilene, TX",4,TX,0,Cross-industry,cross-industry,1235,11-2021,Marketing Managers,...,45.31,72.66,97.35,60130,74980,94240,151130,202490,NaN,NaN
5,10180,"Abilene, TX",4,TX,0,Cross-industry,cross-industry,1235,11-2022,Sales Managers,...,44.89,62.57,87.76,46870,60760,93370,130140,182530,NaN,NaN
6,10180,"Abilene, TX",4,TX,0,Cross-industry,cross-industry,1235,11-2032,Public Relations Managers,...,35.61,46.71,62.93,55000,63680,74070,97160,130900,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149586,79600,"Worcester, MA-CT",4,MA,0,Cross-industry,cross-industry,1235,53-7062,"Laborers and Freight, Stock, and Material Move...",...,19.99,22.59,27.13,33730,36870,41570,47000,56420,NaN,NaN
149587,79600,"Worcester, MA-CT",4,MA,0,Cross-industry,cross-industry,1235,53-7063,Machine Feeders and Offbearers,...,21.87,23.35,26.13,39040,41310,45490,48570,54340,NaN,NaN
149588,79600,"Worcester, MA-CT",4,MA,0,Cross-industry,cross-industry,1235,53-7064,"Packers and Packagers, Hand",...,16.25,17.97,21.93,31200,31200,33800,37370,45610,NaN,NaN
149589,79600,"Worcester, MA-CT",4,MA,0,Cross-industry,cross-industry,1235,53-7065,Stockers and Order Fillers,...,17.57,20.59,22.48,31390,34900,36550,42830,46750,NaN,NaN
149590,79600,"Worcester, MA-CT",4,MA,0,Cross-industry,cross-industry,1235,53-7081,Refuse and Recyclable Material Collectors,...,27.88,29.01,29.46,37710,45110,57980,60350,61270,NaN,NaN

In [12]:
# drop columns
msa_df = msa_df.drop(columns=['AREA_TYPE','NAICS','NAICS_TITLE','I_GROUP', 'OWN_CODE', 'O_GROUP', 'EMP_PRSE', 'LOC_QUOTIENT', 'PCT_TOTAL', 'PCT_RPT', 'MEAN_PRSE', 'ANNUAL','HOURLY'])

In [29]:
msa_df.head()

,area,area_title,prim_state,occ_code,occ_title,tot_emp,jobs_1000,h_mean,a_mean,h_pct10,h_pct25,h_median,h_pct75,h_pct90,a_pct10,a_pct25,a_median,a_pct75,a_pct90
0,10180,"Abilene, TX",TX,11-1011,Chief Executives,40,0.561,115.39,240020,47.35,65.04,97.28,NaN,NaN,98490,135280,202340,NaN,NaN
1,10180,"Abilene, TX",TX,11-1021,General and Operations Managers,2290,31.404,47.35,98480,16.56,23.77,37.19,57.85,86.97,34440,49430,77360,120330,180900
2,10180,"Abilene, TX",TX,11-2021,Marketing Managers,120,1.675,55.91,116290,28.91,36.05,45.31,72.66,97.35,60130,74980,94240,151130,202490
3,10180,"Abilene, TX",TX,11-2022,Sales Managers,250,3.433,51.83,107810,22.54,29.21,44.89,62.57,87.76,46870,60760,93370,130140,182530
4,10180,"Abilene, TX",TX,11-2032,Public Relations Managers,30,0.42,42.76,88930,26.44,30.62,35.61,46.71,62.93,55000,63680,74070,97160,130900

In [22]:
# lowercase columns
msa_df.columns = msa_df.columns.str.lower()

# Preprocessing - rpp

In [14]:
# read in data
rpp_df = pd.read_csv("../data/raw/rpp_2023.csv", skiprows=3)

In [15]:
# filter only line code 1 (RPP for all items)
rpp_df = rpp_df[(rpp_df["LineCode"] == 1) | (rpp_df["LineCode"] == 3)]

In [16]:
# rename 2023 column to RPP for clarity
rpp_df.rename(columns={'2023': 'RPP'}, inplace=True)

In [17]:
# filtering the RPP dataset to only Metropolitan Statistical Areas (MSAs)
rpp_df = rpp_df[~rpp_df["GeoFIPS"].str.endswith("000")]

In [ ]:
# pivot dataset so that line code 1 and 3 are on same rows
rpp_df = rpp_df.pivot( index=["GeoFIPS", "GeoName"], columns="LineCode", values="RPP" ).reset_index()
rpp_df.columns.name = None

In [19]:
# rename columns for line codes 1 and 3
rpp_df = rpp_df.rename(columns={
    1: "RPPs: All items",
    3: "RPPs: Services: Housing"
})

In [30]:
# lowercase columns
rpp_df.columns = rpp_df.columns.str.lower()

In [39]:
rpp_df.head()

LineCode,geofips,geoname,rpps: all items,rpps: services: housing
,,,,
0,00999,United States (Nonmetropolitan Portion) *,88.347,58.886
1,10180,"Abilene, TX (Metropolitan Statistical Area)",90.394,73.631
2,10420,"Akron, OH (Metropolitan Statistical Area)",92.924,77.456
3,10500,"Albany, GA (Metropolitan Statistical Area)",86.491,50.046
4,10540,"Albany, OR (Metropolitan Statistical Area)",104.740,108.588

# Output all files